version: "3.1"

services:
  api:
    image: microservices-api
    ports:
      - "3001:3001"

  cache-service:
    image: microservices-cache-service
    # port:
    #   - ""

  enrich-data-service:
    image: microservices-enrich-data-service

  web-service:
    image: microservices-web-service

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  redis:
    hostname: redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/.data/redis:/var/lib/redis
      # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
